#! /usr/bin/bash

read -p "please enter your database name:" dbName

if [[ $dbName =~ ^[a-zA-Z$_][a-zA-Z0-9$_]+$ ]];
then 
if [[ -d $dbName ]];
then
rm -r $dbName
echo "database has been removed"
else
echo "database does not exist"
fi
else
echo "name is not valid"
dropDB
fi
